general:
  token: 
  group_name: deti_tmij
  dir_name: godless_dependence
  logo: data/logotip_deti.png
  offset: 0
  circles: 4
  ver_api: 5.131
  stop_slova: источник,https,http,club
  wotemark: True